version: '3.5'

services:
  # PHP Craft CMS Service
  craft-cms: &api
    build: .
    volumes:
      - .:/var/www/app
      # - ~/.aws:/root/.aws
      # - ~/.aws:/var/www/.aws
      # - ./etc/php:/usr/local/etc/php
      # - ./etc/php-fpm.d:/usr/local/etc/php-fpm.d
      # - ./etc/supervisord:/etc/supervisor/conf.d
      # - ./etc/nginx/sites-available:/etc/nginx/sites-enabled
    networks:
      - proxy-network
    environment:
      DB_SCHEMA: public
      DATABASE_TYPE: pgsql
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASS: b0Wt1eD3v5
      DATABASE_NAME: bowtie_craft_local
      APP_NAME: craft-cms
      APP_ENV: local
      # LOG_CHANNEL: stack
      APP_URL: https://craft.bowtie.dev
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.rule=Host:craft.bowtie.dev"
      - "traefik.port=80"

# Docker Networks
networks:
  proxy-network:
    external:
      name: bowtie-dev
